### ISSUE TITLE
Can you provide a more detailed build instructions?

### ISSUE THREAD

**Issue by VLiu7** [esa/LADDS#142]
Hi, thank you very much for providing such interesting work. 

Can you provide more detailed build instructions and hardware requirements? Is it possible to run on a normal ubuntu server?

In `CC=clang CXX=clang++ ccmake .` Can you provide an example of how to set each parameter?

I feel like a lot of people are not familiar with building C++ projects, and a more detailed build procedure would be helpful.

**Comment by VLiu7** [comment]
I tried to configure the parameters in `CC=clang CXX=clang++ ccmake .` and run `make` at./LADDS, but I cannot get `./ladds`.

**Comment by FG-TUM** [comment]
Thanks for your interest!
> Is it possible to run on a normal ubuntu server?
Our CI runs on GitHub'S default ubuntu docker containers so yes.

> Can you provide an example of how to set each parameter?
You set them through the interactive `ccmake` interface. However, all parameters use sane defaults so you should only need to change something if you know what you are doing. For details on how to use CMake please refer to [their documentation](https://cmake.org/cmake/help/latest/guide/tutorial/A%20Basic%20Starting%20Point.html#build-and-run).

I noticed that you write `cmake .`.  It is highly advisable to do an out-of-source build to avoid conflicts. Clean any artifacts and start over.

Apart from that there really is not more to the build process than running `cmake` and `make`.

**Comment by VLiu7** [comment]
Thanks for your quick reply, I got it.

It's my bad, I mistakenly thought that `ladds` would be in the home or build directory, but later found out that it was actually in `. /build/src/ladds/ladds`. 

Maybe it would be better to make a copy in the home directory when building? Just a small suggestion.

Thank you very much for providing such an open source model of debris evolution, it is very helpful for our research.
